on:
  workflow_dispatch:
  release:
    types:
      - created

name:  npmjs - package publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: nick-fields/retry@v2
        with:
          max_attempts: 10
          timeout_minutes: 10
          command: |
            npm config set @sencha:registry https://npm.sencha.com/
            npm config set //npm.sencha.com/:_authToken=${{ secrets.SENCHA_ACCESS_TOKEN }}
            npm ci --save-dev
            npm run build
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}