on:
  workflow_dispatch:
  release:
    types:
      - created

name: github - package publish

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: nick-fields/retry@v2
        with:
          max_attempts: 10
          timeout_minutes: 1
          command: |
            npm config set @sencha:registry https://npm.sencha.com/
            npm config set //npm.sencha.com/:_authToken=${{ secrets.SENCHA_ACCESS_TOKEN }}
            npm ci --save-dev
            npm run build
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@conjoon'
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}